### ISSUE TITLE
Idée

### ISSUE THREAD

**Issue by FullGreenGN** [Yellow375/affichageTAG#2]
Salut !

Tu aurais pu faire des canvas au lieu d'utiliser des images pour chaque lignes

**Comment by Mantamo** [comment]
Hello !
En effet je n'y avais pas pensé je dev ça quand j'en aurai le temps !
Merci de ton idée !
Yellow

**Comment by Mantamo** [comment]
J'ai fait la modification de mon côté ça n'est pas encore publié sur GH mais tu pourras le retrouver sur le site de dev -> https://dev.tag.noahyellow.me ^^
